// songBirdData
export const RESET_INITIAL_SONG_BIRD_DATA = 'RESET_INITIAL_SONG_BIRD_DATA';
export const ADD_SCORE = 'ADD_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
export const INCREASE_LEVEL = 'INCREASE_LEVEL';
export const RESET_LEVEL = 'RESET_LEVEL';
export const SET_ANSWERS = 'SET_ANSWERS';
export const SET_IS_READY_FOR_NEXT_LEVEL = 'SET_IS_READY_FOR_NEXT_LEVEL';
export const SET_RIGHT_BIRD = 'SET_RIGHT_BIRD';
export const RESET_ADDITIONAL_SCORE = 'RESET_ADDITIONAL_SCORE';
export const DECREASE_ADDITIONAL_SCORE = 'DECREASE_ADDITIONAL_SCORE';
export const SET_IS_CONGRATULATIONS_SHOWED = 'SET_IS_CONGRATULATIONS_SHOWED';
export const SET_CURRENT_BIRD = 'SET_CURRENT_BIRD';

// initialbirdAnswerBlock
export const RESET_BIRD_ANSWER_BLOCK = 'RESET_BIRD_ANSWER_BLOCK';
export const PRESS_BIRD_ANSWER_BUTTON = 'PRESS_BIRD_ANSWER_BUTTON';
